name: imagecomparer # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Image viewer for comparing two images or two image series. 
description: Image viewer for comparing two images or two image series. |

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
    gtk-3-themes:
        interface: content
        target: $SNAP/usr/share/themes
        default-provider: gtk-common-themes
    icon-themes:
        interface: content
        target: $SNAP/usr/share/icons
        default-provider: gtk-common-themes
    # python3:
    #     interface: content
    #     content: python3
    #     target: python
    #     default-provider: python36-jamesh


apps:
    imagecomparer:
        command: desktop-launch imagecomparer
        plugs:
            - opengl
            - desktop
            - desktop-legacy
            - x11
            - wayland
            - home
            - network
            - icon-themes
            - gsettings


parts:

    imagecomparer:
        plugin: cmake
        source: .
        source-type: git
        build-packages:
            - libpng-dev
            - libopencv-dev
            - libqt5svg5-dev
            - libboost-all-dev
            - libomp-dev
            - zlib1g-dev
            - libqt5opengl5-dev
            - libeigen3-dev
            - libqt5widgets5
            - libqt5core5a
            - libgraphite2-dev
            - qtchooser
            - freeglut3-dev
            - libx11-dev
            - libxmu-dev
            - libxi-dev
            - libgl1-mesa-glx
            - libglu1-mesa
            - libglu1-mesa-dev
            - libglfw3-dev
            - libgles2-mesa-dev
            - libqt5printsupport5
            - libpython-dev
            - python-dev
            - python-tk
            - libqt5svg5
            - qtbase5-dev
            - dpkg-dev
        stage-packages:
            # Here for the plugins-- they're not linked in automatically.
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5 # for loading icon themes which are svg
            - appmenu-qt5
            - python-tk
            - python-skimage
        after: 
            - desktop-qt5
            - qt5conf
            - qt5
            - pythonpackages


    qt5:
         source: git://github.com/ubuntu/snapcraft-desktop-helpers
         source-subdir: qt
         make-parameters: ["FLAVOR=qt5"]
         plugin: make
         build-packages:
             - qtbase5-dev
             - dpkg-dev

    pythonpackages:
        plugin: python
        python-version: python2
        python-packages: [matplotlib,numpy, pydicom]

